// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: delivery/models.proto

package delivery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverStatus int32

const (
	DriverStatus_DRIVER_STATUS_UNDEFINED DriverStatus = 0
	DriverStatus_DRIVER_STATUS_OFFLINE   DriverStatus = 1
	DriverStatus_DRIVER_STATUS_AVAILABLE DriverStatus = 2
	DriverStatus_DRIVER_STATUS_SERVING   DriverStatus = 3
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "DRIVER_STATUS_UNDEFINED",
		1: "DRIVER_STATUS_OFFLINE",
		2: "DRIVER_STATUS_AVAILABLE",
		3: "DRIVER_STATUS_SERVING",
	}
	DriverStatus_value = map[string]int32{
		"DRIVER_STATUS_UNDEFINED": 0,
		"DRIVER_STATUS_OFFLINE":   1,
		"DRIVER_STATUS_AVAILABLE": 2,
		"DRIVER_STATUS_SERVING":   3,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_models_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_delivery_models_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{0}
}

type RotationType int32

const (
	RotationType_Rotation_Type_WLH RotationType = 0
	RotationType_Rotation_Type_LWH RotationType = 1
	RotationType_Rotation_Type_LHW RotationType = 2
	RotationType_Rotation_Type_HLW RotationType = 3
	RotationType_Rotation_Type_HWL RotationType = 4
	RotationType_Rotation_Type_WHL RotationType = 5
)

// Enum value maps for RotationType.
var (
	RotationType_name = map[int32]string{
		0: "Rotation_Type_WLH",
		1: "Rotation_Type_LWH",
		2: "Rotation_Type_LHW",
		3: "Rotation_Type_HLW",
		4: "Rotation_Type_HWL",
		5: "Rotation_Type_WHL",
	}
	RotationType_value = map[string]int32{
		"Rotation_Type_WLH": 0,
		"Rotation_Type_LWH": 1,
		"Rotation_Type_LHW": 2,
		"Rotation_Type_HLW": 3,
		"Rotation_Type_HWL": 4,
		"Rotation_Type_WHL": 5,
	}
)

func (x RotationType) Enum() *RotationType {
	p := new(RotationType)
	*p = x
	return p
}

func (x RotationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RotationType) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_models_proto_enumTypes[1].Descriptor()
}

func (RotationType) Type() protoreflect.EnumType {
	return &file_delivery_models_proto_enumTypes[1]
}

func (x RotationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RotationType.Descriptor instead.
func (RotationType) EnumDescriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{1}
}

type LatLng struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{0}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type VehicleCapacity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight int32 `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Length int32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VehicleCapacity) Reset() {
	*x = VehicleCapacity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCapacity) ProtoMessage() {}

func (x *VehicleCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCapacity.ProtoReflect.Descriptor instead.
func (*VehicleCapacity) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleCapacity) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *VehicleCapacity) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *VehicleCapacity) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VehicleCapacity) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GoodsMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight int32  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Length int32  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GoodsMetadata) Reset() {
	*x = GoodsMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsMetadata) ProtoMessage() {}

func (x *GoodsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsMetadata.ProtoReflect.Descriptor instead.
func (*GoodsMetadata) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsMetadata) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GoodsMetadata) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GoodsMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GoodsMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type TimeWindow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{3}
}

func (x *TimeWindow) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TimeWindow) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type VehicleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleCapacity *VehicleCapacity `protobuf:"bytes,1,opt,name=vehicle_capacity,json=vehicleCapacity,proto3" json:"vehicle_capacity,omitempty"`
	BoxItems        []*BoxItem       `protobuf:"bytes,2,rep,name=box_items,json=boxItems,proto3" json:"box_items,omitempty"`
}

func (x *VehicleState) Reset() {
	*x = VehicleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleState) ProtoMessage() {}

func (x *VehicleState) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleState.ProtoReflect.Descriptor instead.
func (*VehicleState) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{4}
}

func (x *VehicleState) GetVehicleCapacity() *VehicleCapacity {
	if x != nil {
		return x.VehicleCapacity
	}
	return nil
}

func (x *VehicleState) GetBoxItems() []*BoxItem {
	if x != nil {
		return x.BoxItems
	}
	return nil
}

type BoxItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight       int32        `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Width        int32        `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Length       int32        `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Height       int32        `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	RotationType RotationType `protobuf:"varint,5,opt,name=rotation_type,json=rotationType,proto3,enum=delivery.RotationType" json:"rotation_type,omitempty"`
	Pos          []int32      `protobuf:"varint,6,rep,packed,name=pos,proto3" json:"pos,omitempty"`
}

func (x *BoxItem) Reset() {
	*x = BoxItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxItem) ProtoMessage() {}

func (x *BoxItem) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxItem.ProtoReflect.Descriptor instead.
func (*BoxItem) Descriptor() ([]byte, []int) {
	return file_delivery_models_proto_rawDescGZIP(), []int{5}
}

func (x *BoxItem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BoxItem) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoxItem) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BoxItem) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoxItem) GetRotationType() RotationType {
	if x != nil {
		return x.RotationType
	}
	return RotationType_Rotation_Type_WLH
}

func (x *BoxItem) GetPos() []int32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_delivery_models_proto protoreflect.FileDescriptor

var file_delivery_models_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x06, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6e, 0x67,
	0x22, 0x6f, 0x0a, 0x0f, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x7e, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x35,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x41, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x0f, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x09,
	0x62, 0x6f, 0x78, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x42, 0x6f, 0x78, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x08, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xb6, 0x01, 0x0a,
	0x07, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x2a, 0x7e, 0x0a, 0x0c, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x1b, 0x0a,
	0x17, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x52,
	0x49, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x4e, 0x47, 0x10, 0x03, 0x2a, 0x98, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x4c, 0x48, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4c,
	0x57, 0x48, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4c, 0x48, 0x57, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x48, 0x4c, 0x57,
	0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x48, 0x57, 0x4c, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x48, 0x4c, 0x10, 0x05,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x68, 0x74, 0x31, 0x30, 0x32, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_delivery_models_proto_rawDescOnce sync.Once
	file_delivery_models_proto_rawDescData = file_delivery_models_proto_rawDesc
)

func file_delivery_models_proto_rawDescGZIP() []byte {
	file_delivery_models_proto_rawDescOnce.Do(func() {
		file_delivery_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_models_proto_rawDescData)
	})
	return file_delivery_models_proto_rawDescData
}

var file_delivery_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_delivery_models_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_delivery_models_proto_goTypes = []interface{}{
	(DriverStatus)(0),             // 0: delivery.DriverStatus
	(RotationType)(0),             // 1: delivery.RotationType
	(*LatLng)(nil),                // 2: delivery.LatLng
	(*VehicleCapacity)(nil),       // 3: delivery.VehicleCapacity
	(*GoodsMetadata)(nil),         // 4: delivery.GoodsMetadata
	(*TimeWindow)(nil),            // 5: delivery.TimeWindow
	(*VehicleState)(nil),          // 6: delivery.VehicleState
	(*BoxItem)(nil),               // 7: delivery.BoxItem
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_delivery_models_proto_depIdxs = []int32{
	8, // 0: delivery.TimeWindow.started_at:type_name -> google.protobuf.Timestamp
	8, // 1: delivery.TimeWindow.ended_at:type_name -> google.protobuf.Timestamp
	3, // 2: delivery.VehicleState.vehicle_capacity:type_name -> delivery.VehicleCapacity
	7, // 3: delivery.VehicleState.box_items:type_name -> delivery.BoxItem
	1, // 4: delivery.BoxItem.rotation_type:type_name -> delivery.RotationType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_delivery_models_proto_init() }
func file_delivery_models_proto_init() {
	if File_delivery_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatLng); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleCapacity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeWindow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoxItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_models_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_models_proto_goTypes,
		DependencyIndexes: file_delivery_models_proto_depIdxs,
		EnumInfos:         file_delivery_models_proto_enumTypes,
		MessageInfos:      file_delivery_models_proto_msgTypes,
	}.Build()
	File_delivery_models_proto = out.File
	file_delivery_models_proto_rawDesc = nil
	file_delivery_models_proto_goTypes = nil
	file_delivery_models_proto_depIdxs = nil
}
